version: 0.0
os: linux
files:
  - source: testproject.war
    destination: /var/lib/tomcat8/webapps
hooks:
  BeforeInstall:   
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root