version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html
hooks:
  BeforeInstall:   
    - location: /home/ec2-user/scripts/stop_server.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/scripts/start_server.sh
      timeout: 120
      runas: root